<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Scipy-for-Linear-Algebra" data-toc-modified-id="Scipy-for-Linear-Algebra-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Scipy for Linear Algebra</a></span><ul class="toc-item"><li><span><a href="#Create-Vectors-and-Matrices" data-toc-modified-id="Create-Vectors-and-Matrices-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Create Vectors and Matrices</a></span><ul class="toc-item"><li><span><a href="#Create-Array-from-Python-Lists" data-toc-modified-id="Create-Array-from-Python-Lists-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Create Array from Python Lists</a></span></li><li><span><a href="#Creat-Numpy-Array-IO-with-files" data-toc-modified-id="Creat-Numpy-Array-IO-with-files-1.1.2"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>Creat Numpy Array IO with files</a></span></li></ul></li><li><span><a href="#Basic-Matrix-Routines" data-toc-modified-id="Basic-Matrix-Routines-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Basic Matrix Routines</a></span></li><li><span><a href="#Operations-Between-Vectors-and-Matrices" data-toc-modified-id="Operations-Between-Vectors-and-Matrices-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Operations Between Vectors and Matrices</a></span></li><li><span><a href="#Matrix-Decompositions" data-toc-modified-id="Matrix-Decompositions-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Matrix Decompositions</a></span></li></ul></li></ul></div>

# Scipy for Linear Algebra

Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like Pandas ([Chapter 3](03.00-Introduction-to-Pandas.ipynb)) are built around the NumPy array.
This section will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays.
While the types of operations shown here may seem a bit dry and pedantic, they comprise the building blocks of many other examples used throughout the book.
Get to know them well!

We'll cover a few categories of basic array manipulations here:

- *Attributes of arrays*: Determining the size, shape, memory consumption, and data types of arrays
- *Indexing of arrays*: Getting and setting the value of individual array elements
- *Slicing of arrays*: Getting and setting smaller subarrays within a larger array
- *Reshaping of arrays*: Changing the shape of a given array
- *Joining and splitting of arrays*: Combining multiple arrays into one, and splitting one array into many

## Create Vectors and Matrices

In [5]:
import numpy as np
from scipy import linalg, sparse
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


### Create Array from Python Lists
Numpy arrays (1D) can be directly created from Python list. However, while python lists can hold different types, , NumPy array can only allow the same type. If types do not match, NumPy will upcast if possible (here, integers are up-cast to floating point) or give exception otherwise.

In [3]:
# integer array:
np.array([1, 4, 2, 5, 3])
a = np.array([1, 4, 2, 5, 3])
# array data type and shape
a.dtype
a.shape

# mixed type array, upcasting will be used
np.array([1, 4.4, 2.2, 5, 3])

# mixed type array, upcasting will be used
np.array([1, 4.4, 'string', 5, True])

# exception will throw when upcasting is not possible
np.array([1, 4.4, 'string', 5, list([1,2,3])])





array([1, 4, 2, 5, 3])

dtype('int32')

(5,)

array([1. , 4.4, 2.2, 5. , 3. ])

array(['1', '4.4', 'string', '5', 'True'], dtype='<U32')

ValueError: setting an array element with a sequence

### Creat Numpy Array IO with files

Numpy arries can be created from txt and csv files.

In [ ]:
a = np.random.random((10,10))

np.save('numpyTest.txt',a,delimiter=',')
np.save('numpyTest.csv',a,delimiter=',')


b = np.genfromtxt("numpyTest.csv",delimiter=',')
c = np.genfromtxt("numpyTest.txt",delimiter=',')

## Basic Matrix Routines

Basic matrix routines include matrix inverse, transpose, trace, norm, rank, determinant, and linear system solutions.

In [6]:
A = np.matrix([[1, 2],[3,4]])
A.I
linalg.inv(A)

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [7]:
A = np.matrix([[1, 2],[3,4]])
A.H
A.T
np.transpose(A)

matrix([[1, 3],
        [2, 4]])

matrix([[1, 3],
        [2, 4]])

matrix([[1, 3],
        [2, 4]])

Another useful attribute is the ``dtype``, the data type of the array (which we discussed previously in [Understanding Data Types in Python](02.01-Understanding-Data-Types.ipynb)):

In [3]:
print("dtype:", x3.dtype)

dtype: int64


Other attributes include ``itemsize``, which lists the size (in bytes) of each array element, and ``nbytes``, which lists the total size (in bytes) of the array:

In [4]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In general, we expect that ``nbytes`` is equal to ``itemsize`` times ``size``.

## Operations Between Vectors and Matrices

## Matrix Decompositions

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar.
In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [5]:
x1

array([5, 0, 3, 3, 7, 9])

In [6]:
x1[0]

5

In [7]:
x1[4]

7

To index from the end of the array, you can use negative indices:

In [8]:
x1[-1]

9

In [9]:
x1[-2]

7

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [10]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [11]:
x2[0, 0]

3

In [12]:
x2[2, 0]

1

In [13]:
x2[2, -1]

7

Values can also be modified using any of the above index notation: